name: credit-types-simplex-method
version: '3.8'
services:
  devcontainer:
    container_name: credit-types-simplex-method
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
